 # SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 # SPDX-License-Identifier: LicenseRef-NvidiaProprietary
 #
 # NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
 # property and proprietary rights in and to this material, related
 # documentation and any modifications thereto. Any use, reproduction,
 # disclosure or distribution of this material and related documentation
 # without an express license agreement from NVIDIA CORPORATION or
 # its affiliates is strictly prohibited.


VAL_COUNT: 3
ADR_COUNT: 2
U_NET_MAX: 5
CPU_COUNT: 2
CACHE_L1_COUNT: 2
DIR_COUNT: 2
INSTR_COUNT: 3
CHECK_EXPECTED: 1
ADDR_TO_DIR:
  - ADDR: 0
    DIR: 0
  - ADDR: 1
    DIR: 0
LITMUS_TEST:
  - CPU_IDX: 0
    INSTR_STREAM:
      - INSTR_IDX: 0
        INSTR_ACC: "store"
        INSTR_CST: "RLX"
        INSTR_ADDR: 0
        INSTR_VAL: 1
      - INSTR_IDX: 1
        INSTR_ACC: "store"
        INSTR_CST: "REL"
        INSTR_ADDR: 1
        INSTR_VAL: 1
      - INSTR_IDX: 2
        INSTR_ACC: "load"
        INSTR_CST: "RLX"
        INSTR_ADDR: 1
        INSTR_VAL: 0       
  - CPU_IDX: 1
    INSTR_STREAM:
      - INSTR_IDX: 0
        INSTR_ACC: "store"
        INSTR_CST: "REL"
        INSTR_ADDR: 1
        INSTR_VAL: 2
      - INSTR_IDX: 1
        INSTR_ACC: "load"
        INSTR_CST: "ACQ"
        INSTR_ADDR: 0
        INSTR_VAL: 0
EXPECTED_OUTCOME:
  - OUTCOME_IDX: 0
    LOAD_OUTCOME:
    - CPU_IDX: 0
      INSTR_IDX: 2
      INSTR_VAL: 2
    - CPU_IDX: 1
      INSTR_IDX: 1
      INSTR_VAL: 0
# for RRC
TS_MAX: 2
CNT_MAX: 2
# AArch64 R
# "PodWWPL CoeLL PodWRLA FreAP"
# Generator=diyone7 (version 7.56)
# Prefetch=0:x=F,0:y=W,1:y=F,1:x=T
# Com=Co Fr
# Orig=PodWWPL CoeLL PodWRLA FreAP
# {
# 0:X1=x; 0:X3=y;
# 1:X1=y; 1:X3=x;
# }
#  P0           | P1           ;
#  MOV W0,#1    | MOV W0,#2    ;
#  STR W0,[X1]  | STLR W0,[X1] ;
#  MOV W2,#1    | LDAR W2,[X3] ;
#  STLR W2,[X3] |              ;
#  LDR W4,[X3]  |              ;
# exists (0:X4=2 /\ 1:X2=0)