ADDR_TO_DIR:
- {ADDR: 0, DIR: 0}
ADR_COUNT: 1
CACHE_L1_COUNT: 2
CHECK_FORBIDDEN: 1
CNT_MAX: 4
CPU_COUNT: 2
DIR_COUNT: 2
FORBIDDEN_OUTCOME:
- LOAD_OUTCOME:
  - {CPU_IDX: 0, INSTR_IDX: 0, INSTR_VAL: 2}
  OUTCOME_IDX: 0
  VAL_OUTCOME:
  - {ADDR: 0, VAL: 2}
INSTR_COUNT: 2
LITMUS_TEST:
- CPU_IDX: 0
  INSTR_STREAM:
  - {INSTR_ACC: load, INSTR_ADDR: 0, INSTR_CST: RLX, INSTR_IDX: 0, INSTR_VAL: 1}
  - {INSTR_ACC: nt_store, INSTR_ADDR: 0, INSTR_CST: RLX, INSTR_IDX: 1, INSTR_VAL: 1}
- CPU_IDX: 1
  INSTR_STREAM:
  - {INSTR_ACC: nt_store, INSTR_ADDR: 0, INSTR_CST: RLX, INSTR_IDX: 0, INSTR_VAL: 2}
TS_MAX: 4
U_NET_MAX: 5
VAL_COUNT: 3
