ADDR_TO_DIR:
- {ADDR: 0, DIR: 0}
- {ADDR: 1, DIR: 1}
ADR_COUNT: 2
CACHE_L1_COUNT: 2
CHECK_EXPECTED: 1
CHECK_FORBIDDEN: 1
CNT_MAX: 1
CPU_COUNT: 2
DIR_COUNT: 2
EXPECTED_OUTCOME:
- LOAD_OUTCOME:
  - {CPU_IDX: 1, INSTR_IDX: 0, INSTR_VAL: 1}
  - {CPU_IDX: 1, INSTR_IDX: 1, INSTR_VAL: 1}
  OUTCOME_IDX: 0
FORBIDDEN_OUTCOME:
- LOAD_OUTCOME:
  - {CPU_IDX: 1, INSTR_IDX: 0, INSTR_VAL: 1}
  - {CPU_IDX: 1, INSTR_IDX: 1, INSTR_VAL: 0}
  OUTCOME_IDX: 0
INSTR_COUNT: 2
LITMUS_TEST:
- CPU_IDX: 0
  INSTR_STREAM:
  - {INSTR_ACC: nt_store, INSTR_ADDR: 0, INSTR_CST: RLX, INSTR_IDX: 0, INSTR_VAL: 1}
  - {INSTR_ACC: store, INSTR_ADDR: 1, INSTR_CST: REL, INSTR_IDX: 1, INSTR_VAL: 1}
- CPU_IDX: 1
  INSTR_STREAM:
  - {INSTR_ACC: load, INSTR_ADDR: 1, INSTR_CST: ACQ, INSTR_IDX: 0, INSTR_VAL: 0}
  - {INSTR_ACC: load, INSTR_ADDR: 0, INSTR_CST: RLX, INSTR_IDX: 1, INSTR_VAL: 0}
TS_MAX: 1
U_NET_MAX: 5
VAL_COUNT: 2
